FROM node:12-alpine3.14
RUN mkdir /app
WORKDIR /app
VOLUME ./src:/app/src
COPY ./package*.json ./
COPY ./.npmrc ./
RUN npm install
# RUN npm install nodemon -g
# COPY ./src ./src
# COPY ./config ./src
# CMD [ "nodemon", "--inspect=0.0.0.0:3321", "./src/index.js" ]
ENTRYPOINT [ "nodemon", "--inspect=0.0.0.0:3321", "./src/index.js" ]
EXPOSE 5000
