FROM node:12-alpine3.14
RUN mkdir /app
WORKDIR /app
# COPY ./package*.json ./
# COPY ./.npmrc ./
# COPY ./src ./src
# COPY ./config ./src
# COPY ./crypto-key ./crypto-key
# CMD [ "nodemon", "--inspect=0.0.0.0:3321", "./src/index.js" ]
COPY ./ ./
RUN npm install
RUN npm install nodemon -g
EXPOSE 5000
ENTRYPOINT [ "nodemon", "--inspect=0.0.0.0:3321", "./src/index.js" ]

