FROM node:12-alpine3.14

RUN mkdir /app
WORKDIR /app

COPY ./package*.json ./
COPY ./.npmrc ./
RUN npm install
RUN npm install nodemon -g
# COPY ./src ./src
# COPY ./config ./src
# CMD [ "nodemon", "--inspect=0.0.0.0:3321", "./src/index.js" ]
# VOLUME /Users/appletxm/Desktop/me/test/koa2-test /app
ENV my_new_test = '9999'
EXPOSE 5000
ENTRYPOINT [ "nodemon", "--inspect=0.0.0.0:3321", "./src/index.js" ]
